# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    session:
        cookie_secure: auto
        cookie_samesite: lax

    rate_limiter:
        api_per_ip:
            policy: 'sliding_window'
            limit: 120
            interval: '1 minute'
        api_per_session:
            policy: 'token_bucket'
            limit: 600
            rate: { amount: 600, interval: '10 minutes' }

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
