name: Deploy via Deployer

on:
    push:
        branches:
            - master
            - staging

jobs:
    deploy:
        name: Deploy to ${{ github.ref_name }}
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4

            -   name: Set up SSH
                uses: webfactory/ssh-agent@v0.9.0
                with:
                    ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            -   name: Install PHP & Composer
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.2'
                    extensions: mbstring, intl, pdo, pdo_mysql
                    tools: composer:v2

            -   name: Install Deployer
                run: composer global require deployer/deployer

            -   name: Deploy
                env:
                    DEPLOYER_BIN: $HOME/.composer/vendor/bin/dep
                run: |
                    $DEPLOYER_BIN deploy ${{ github.ref_name }}
