name: Deploy via Deployer

on:
    push:
        branches:
            - master
            - staging

jobs:
    deploy:
        name: Deploy to ${{ github.ref_name }}
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4

            -   name: Set up SSH
                uses: webfactory/ssh-agent@v0.9.0
                with:
                    ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            -   name: Install PHP & Composer
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.2'
                    extensions: mbstring, intl, pdo, pdo_mysql
                    tools: composer:v2

            -   name: Install Deployer
                run: |
                    composer global require deployer/deployer
                    echo "$HOME/.composer/vendor/bin" >> $GITHUB_PATH

            -   name: Add SSH host key to known_hosts
                run: |
                    mkdir -p ~/.ssh
                    ssh-keyscan -p 2584 da07.qabana.nl >> ~/.ssh/known_hosts

            -   name: Deploy
                run: dep deploy ${{ github.ref_name }}
